version=0.0.1-SNAPSHOT
group=de.abq
java_version=21
# Common
minecraft_version=1.21.1
mod_name=PartiumAPI
mod_author=Cron3x
mod_id=partium
license=LGPL-3.0
credits=
description= A data driven library for adding custom swords and lightsabers with Geckolib\nDocumentation: https://github.com/BambuCraft/PartiumAPI/wiki
mod_homepage=https://modrinth.com/project/partium-api
mod_source=https://github.com/BambuCraft/PartiumAPI
mod_issues=https://github.com/BambuCraft/PartiumAPI/issues

minecraft_version_range=[1.21, 1.22)
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17
# Fabric
fabric_version=0.115.4+1.21.1
fabric_loader_version=0.16.13
# Forge
forge_version=51.0.17
forge_loader_version_range=[51,)
# NeoForge
neoforge_version=21.1.203
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

geckolib_version=4.7.6
geckolib_range=[4.7,)
veil_version=2.3.1